---

- name: "set OS-specific facts"
  when: ansible_os_family == "RedHat"
  set_fact:
    redis_config: "/etc/redis.conf"
    redis_service: "redis.service"

- name: "set OS-specific facts"
  when: ansible_os_family == "Debian"
  set_fact:
    redis_config: "/etc/redis/redis.conf"
    redis_service: "redis-server.service"

