---

- include: "facts.yml"
  tags: "always"

- include: "packages-rhel7.yml"
  tags: "redis-packages"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "7"

- include: "packages-jessie.yml"
  tags: "redis-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "redis.yml"
  tags: "redis-redis"

- include: "optimize.yml"
  tags: "redis-optimize"

