---

- name: "install redis.conf"
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_config }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "restart redis"

- name: "enable and start redis"
  service:
    name: "{{ redis_service }}"
    enabled: True
    state: "started"

