---

# CentOS 7 is stuck on version 2.8.x.
- name: "install jamielinux-redis repository"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  template:
    src: "jamielinux-redis.repo.j2"
    dest: "/etc/yum.repos.d/jamielinux-redis.repo"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "install GPG key"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  copy:
    src: "RPM-GPG-KEY-jamielinux-0x9E5A947BAC2932F8"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-jamielinux-0x9E5A947BAC2932F8"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "check if GPG key has been imported"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  command: "/usr/bin/rpm -qa gpg-pubkey"
  register: "rpm_pubkeys"
  changed_when: False

- name: "import GPG key"
  when: >
    ( ansible_os_family == "RedHat" and ansible_distribution_major_version == "7" )
    and ( "gpg-pubkey-ac2932f8-5566da04" not in rpm_pubkeys.stdout )
  command: "/usr/bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-jamielinux-0x9E5A947BAC2932F8"

- name: "install redis"
  when: ansible_os_family == "RedHat"
  yum:
    name: "redis"
    update_cache: True
    state: "present"

# Debian 8 is stuck on version 2.8.x.
- name: "enable Debian backports repository"
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "8"
  apt_repository:
    repo: "deb http://http.debian.net/debian jessie-backports main"
    state: "present"

- name: "install redis"
  when: ansible_os_family == "Debian" and ansible_distribution_major_version == "8"
  apt:
    name: "redis-server"
    update_cache: True
    default_release: "jessie-backports"
    state: "present"

- name: "install redis"
  when: ansible_os_family == "Debian" and ansible_distribution_major_version != "8"
  apt:
    name: "redis-server"
    update_cache: True
    state: "present"

- name: "install redis.conf"
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_config }}"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "restart redis"

- name: "enable and start redis"
  service:
    name: "{{ redis_service }}"
    enabled: True
    state: "started"

