---

- name: "install redis"
  when: ansible_os_family == "RedHat"
  yum:
    name: "redis"
    update_cache: True
    state: "present"

- name: "install redis"
  when: ansible_os_family == "Debian"
  apt:
    name: "redis-server"
    update_cache: True
    state: "present"

- name: "install /etc/redis.conf"
  template:
    src: "redis.conf.j2"
    dest: "/etc/redis.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - "restart redis"

- name: "enable and start redis"
  service:
    name: "{{ redis_service }}"
    enabled: True
    state: "started"
