---

- name: "set postgres version"
  when: >
    ( ansible_distribution == "Debian" and ansible_distribution_major_version == "8" )
    or ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "15.04" )
  set_fact:
    postgres_version: "9.4"

- name: "set OS-specific facts"
  when: ansible_os_family == "RedHat"
  set_fact:
    postgres_backups: "/var/lib/pgsql/backups"
    postgres_configs: "/var/lib/pgsql/data"
    postgres_datadir: "/var/lib/pgsql/data"
    postgres_service: "postgresql.service"

- name: "set OS-specific facts"
  when: ansible_os_family == "Debian"
  set_fact:
    postgres_backups: "/var/lib/postgresql/backups"
    postgres_configs: "/etc/postgresql/{{ postgres_version }}/main"
    postgres_datadir: "/var/lib/postgresql/{{ postgres_version }}/main"
    postgres_service: "postgresql@{{ postgres_version }}-main.service"

