---

- name: "run locale-gen"
  when: ansible_distribution == "Debian"
  locale_gen:
    name: "{{ postgres_locale }}"
    state: "present"

- name: "initialize database"
  when: ansible_os_family == "RedHat"
  command: >
    /usr/bin/initdb
    --pgdata=/var/lib/pgsql/data
    --locale={{ postgres_locale }}
    --encoding={{ postgres_encoding }}
  args:
    creates: "{{ postgres_datadir }}/PG_VERSION"
  environment:
    LANG: "{{ postgres_locale }}"
    LC_ALL: "{{ postgres_locale }}"
  sudo_user: "postgres"
  notify:
    - "restart postgresql-server"

- name: "initialize database"
  when: ansible_os_family == "Debian"
  command: >
    /usr/bin/pg_createcluster
    --locale={{ postgres_locale }}
    --encoding={{ postgres_encoding }}
    {{ postgres_version }} main
  args:
    creates: "{{ postgres_datadir }}/PG_VERSION"
  environment:
    LANG: "{{ postgres_locale }}"
    LC_ALL: "{{ postgres_locale }}"
  notify:
    - "restart postgresql-server"

- name: "install pg_hba.conf"
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgres_configs }}/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify:
    - "restart postgresql-server"

- name: "install postgresql.conf"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgres_configs }}/postgresql.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify:
    - "restart postgresql-server"

- name: "install /usr/local/bin/take-database-backup"
  template:
    src: "take-database-backup.j2"
    dest: "/usr/local/bin/take-database-backup"
    owner: "postgres"
    group: "postgres"
    mode: "0700"

- name: "create postgres backups directory"
  file:
    dest: "{{ postgres_backups }}"
    owner: "postgres"
    group: "postgres"
    mode: "0700"
    state: "directory"

- name: "schedule database backups"
  when: postgres_auto_backup
  cron:
    name: "backup database"
    minute: "{{ postgres_auto_backup_minute }}"
    hour: "{{ postgres_auto_backup_hour }}"
    job: "/usr/local/bin/take-database-backup"
    user: "postgres"

- name: "enable and start postgres"
  service:
    name: "{{ postgres_service }}"
    enabled: True
    state: "started"

