---

- name: "run locale-gen"
  when: ansible_distribution == "Debian"
  locale_gen:
    name: "{{ postgres_locale }}"
    state: "present"

- name: "initialize database"
  when: ansible_os_family == "RedHat"
  command: "/usr/pgsql-{{ postgres_version }}/bin/postgresql{{ postgres_version_short }}-setup initdb"
  args:
    creates: "{{ postgres_datadir }}/PG_VERSION"
  environment:
    LANG: "{{ postgres_locale }}"
    LC_ALL: "{{ postgres_locale }}"
    PGSETUP_INITDB_OPTIONS: >
      --pgdata={{ postgres_datadir }}
      --locale={{ postgres_locale }}
      --encoding={{ postgres_encoding }}
  notify:
    - "restart postgresql-server"

- name: "initialize database"
  when: ansible_os_family == "Debian"
  command: >
    /usr/bin/pg_createcluster
    --locale={{ postgres_locale }}
    --encoding={{ postgres_encoding }}
    {{ postgres_version }} main
  args:
    creates: "{{ postgres_datadir }}/PG_VERSION"
  environment:
    LANG: "{{ postgres_locale }}"
    LC_ALL: "{{ postgres_locale }}"
  notify:
    - "restart postgresql-server"

- name: "install pg_hba.conf"
  template:
    src: "pg_hba.conf.j2"
    dest: "{{ postgres_configs }}/pg_hba.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify:
    - "restart postgresql-server"

- name: "install postgresql.conf"
  template:
    src: "postgresql.conf.j2"
    dest: "{{ postgres_configs }}/postgresql.conf"
    owner: "postgres"
    group: "postgres"
    mode: "0600"
  notify:
    - "restart postgresql-server"

