---

- name: "install packages required for SELinux"
  when: ansible_selinux.status != "disabled" and ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    - "policycoreutils"
    - "policycoreutils-python"

- name: "install packages required for SELinux"
  when: ansible_selinux.status != "disabled" and ansible_os_family == "Debian"
  apt:
    name: "policycoreutils"
    update_cache: True
    state: "present"

- name: "configure SELinux file contexts for PostgreSQL executables"
  when: ansible_selinux.status != "disabled"
  command: >
    /usr/sbin/semanage fcontext -a -t postgresql_exec_t
    "/usr/pgsql-[0-9.]+/bin/.*"
  args:
    creates: "/root/.ansible_semanage_postgresql_exec_t"
  notify:
    - "touch /root/.ansible_semanage_postgresql_exec_t"

- name: "configure SELinux file contexts for PostgreSQL log files"
  when: ansible_selinux.status != "disabled"
  command: >
    /usr/sbin/semanage fcontext -a -t postgresql_log_t
    "/var/lib/pgsql/[0-9.]+/data/pg_log(/.*)?"
  args:
    creates: "/root/.ansible_semanage_postgresql_log_t"
  notify:
    - "touch /root/.ansible_semanage_postgresql_log_t"

- name: "install packages"
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    - "postgresql{{ postgres_version_short }}"
    - "postgresql{{ postgres_version_short }}-contrib"
    - "postgresql{{ postgres_version_short }}-devel"
    - "postgresql{{ postgres_version_short }}-server"
    - "python-psycopg2"

- name: "install packages"
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: True
    default_release: "jessie-pgdg"
    state: "present"
  with_items:
    - "postgresql-{{ postgres_version }}"
  register: install_postgresql

- name: "drop default cluster"
  when: ansible_os_family == "Debian" and install_postgresql.changed
  command: "/usr/bin/pg_dropcluster --stop {{ postgres_version }} main"

- name: "install packages"
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: True
    default_release: "jessie-pgdg"
    state: "present"
  with_items:
    - "postgresql-client-{{ postgres_version }}"
    - "postgresql-contrib-{{ postgres_version }}"
    - "postgresql-server-dev-{{ postgres_version }}"
    - "python-psycopg2"

