---

- name: "unbound"
  hosts: "all"
  sudo: True
  gather_facts: True

  roles:
    - role: "unbound"
      tags: ["unbound"]


- name: "postgres"
  hosts: "postgres"
  sudo: True
  gather_facts: True

  roles:
    - role: "postgres-discourse"
      tags: ["postgres-discourse"]


- name: "redis"
  hosts: "redis"
  sudo: True
  gather_facts: True

  roles:
    - role: "redis"
      tags: ["redis"]


- name: "discourse"
  hosts: "discourse"
  sudo: True
  gather_facts: True

  roles:
    - role: 'discourse'
      tags: ['discourse']

    - role: "nginx-discourse"
      tags: ["nginx-discourse"]

    - role: "opendkim"
      tags: ["opendkim"]
      when: discourse_smtp_address == 'localhost' and dkim_enabled

    - role: "postfix"
      tags: ["postfix"]
      when: discourse_smtp_address == 'localhost'


