---

- include: "packages-rhel7.yml"
  tags: "unbound-packages"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "7"

- include: "packages-f22.yml"
  tags: "unbound-packages"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "22"

- include: "packages-jessie.yml"
  tags: "unbound-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "packages-jessie.yml"
  tags: "unbound-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_version == "15.04"

- include: "configs.yml"
  tags: "unbound-configs"

- include: "services.yml"
  tags: "unbound-services"

