---

- include: "facts.yml"
  tags: "always"

- include: "user.yml"
  tags: "discourse-user"

- include: "packages.yml"
  tags: "discourse-packages"

- include: "postgres-redhat.yml"
  tags: "discourse-postgres"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "7"

- include: "postgres-jessie.yml"
  tags: "discourse-postgres"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "app.yml"
  tags: "discourse-app"

- include: "bundler.yml"
  tags: "discourse-bundler"

- include: "npm.yml"
  tags: "discourse-npm"

- include: "db.yml"
  tags: "discourse-db"

- include: "assets.yml"
  tags: "discourse-assets"

- include: "unicorn.yml"
  tags: "discourse-unicorn"

