---

- name: "install npm"
  when: ansible_os_family == "RedHat"
  yum:
    name: "npm"
    update_cache: True
    state: "present"

- name: "install npm"
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    - "npm"
    - "nodejs-legacy" # modules break without the /usr/bin/node symlink

- name: "install npm modules"
  npm:
    name: "{{ item }}"
    production: True
    path: "/home/discourse"
  sudo_user: "discourse"
  with_items:
    - "svgo"
    - "uglify-js"

