---

# Some of these may not strictly be necessary.
- name: "install packages for building Discourse"
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    # Basic development:
    - "autoconf"
    - "automake"
    - "binutils"
    - "bison"
    - "byacc"
    - "gcc"
    - "gcc-c++"
    - "gettext"
    - "glibc-devel"
    - "libtool"
    - "make"
    - "patch"
    - "pkgconfig"
    # Ruby:
    - "gdbm-devel"
    - "libffi-devel"
    - "libyaml-devel"
    - "ncurses-devel"
    - "openssl-devel"
    - "readline-devel"
    - "zlib-devel"
    # Unicorn:
    - "jemalloc"
    # image_optim:
    - "advancecomp"
    - "gifsicle"
    - "jhead"
    - "jpegoptim"
    - "libjpeg"
    - "libjpeg-turbo-utils"
    - "optipng"
    - "pngcrush"
    - "pngquant"
    # Other:
    - "ImageMagick"
    - "git"
    - "gzip"
    - "libcurl-devel"
    - "policycoreutils"
    - "policycoreutils-python"

# Some of these may not strictly be necessary.
- name: "install packages for building Discourse"
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    # Basic development:
    - "autoconf"
    - "automake"
    - "binutils"
    - "bison"
    - "byacc"
    - "gcc"
    - "g++"
    - "gettext"
    - "libtool"
    - "make"
    - "libc6-dev"
    - "patch"
    - "pkg-config"
    # Ruby:
    - "libffi-dev"
    - "libgdbm3"
    - "libgdbm-dev"
    - "libncurses5-dev"
    - "libreadline6-dev"
    - "libssl-dev"
    - "libyaml-dev"
    - "zlib1g-dev"
    # Unicorn:
    - "libjemalloc1"
    # image_optim:
    - "advancecomp"
    - "gifsicle"
    - "jhead"
    - "jpegoptim"
    - "libjpeg-turbo-progs"
    - "optipng"
    - "pngcrush"
    - "pngquant"
    # Other:
    - "git"
    - "gzip"
    - "imagemagick"
    - "libcurl3"
    - "policycoreutils"

- name: "install packages"
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    - "postgresql{{ postgres_version_short }}"
    - "postgresql{{ postgres_version_short }}-devel"

- name: "install packages"
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    - "postgresql-client-{{ postgres_version }}"
    - "postgresql-server-dev-{{ postgres_version }}"

