---

# Some of these may not strictly be necessary.
- name: "install packages for building Discourse"
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    # Basic development:
    - "autoconf"
    - "automake"
    - "binutils"
    - "bison"
    - "byacc"
    - "gcc"
    - "gcc-c++"
    - "gettext"
    - "glibc-devel"
    - "libtool"
    - "make"
    - "patch"
    - "pkgconfig"
    # Ruby:
    - "gdbm-devel"
    - "libffi-devel"
    - "libyaml-devel"
    - "ncurses-devel"
    - "openssl-devel"
    - "readline-devel"
    - "zlib-devel"
    # Unicorn:
    - "jemalloc"
    # image_optim:
    - "advancecomp"
    - "gifsicle"
    - "jhead"
    - "jpegoptim"
    - "libjpeg"
    - "libjpeg-turbo-utils"
    - "optipng"
    - "pngcrush"
    - "pngquant"
    # Other:
    - "ImageMagick"
    - "git"
    - "gzip"
    - "libcurl-devel"
    - "policycoreutils"

# Some of these may not strictly be necessary.
- name: "install packages for building Discourse"
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    # Basic development:
    - "autoconf"
    - "automake"
    - "binutils"
    - "bison"
    - "byacc"
    - "gcc"
    - "g++"
    - "gettext"
    - "libtool"
    - "make"
    - "libc6-dev"
    - "patch"
    - "pkg-config"
    # Ruby:
    - "libffi-dev"
    - "libgdbm3"
    - "libgdbm-dev"
    - "libncurses5-dev"
    - "libreadline6-dev"
    - "libssl-dev"
    - "libyaml-dev"
    - "zlib1g-dev"
    # Unicorn:
    - "libjemalloc1"
    # image_optim:
    - "advancecomp"
    - "gifsicle"
    - "jhead"
    - "jpegoptim"
    - "libjpeg-turbo-progs"
    - "optipng"
    - "pngcrush"
    - "pngquant"
    # Other:
    - "git"
    - "gzip"
    - "imagemagick"
    - "libcurl3"
    - "policycoreutils"

# CentOS 7 is stuck on version 9.2.x.
- name: "install jamielinux-postgresql repository"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  template:
    src: "jamielinux-postgresql.repo.j2"
    dest: "/etc/yum.repos.d/jamielinux-postgresql.repo"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "install GPG key"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  copy:
    src: "RPM-GPG-KEY-jamielinux-0x9E5A947BAC2932F8"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-jamielinux-0x9E5A947BAC2932F8"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "check if GPG key has been imported"
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
  command: "/usr/bin/rpm -qa gpg-pubkey"
  register: "rpm_pubkeys"
  changed_when: False

- name: "import GPG key"
  when: >
    ( ansible_os_family == "RedHat" and ansible_distribution_major_version == "7" )
    and ( "gpg-pubkey-ac2932f8-5566da04" not in rpm_pubkeys.stdout )
  command: "/usr/bin/rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-jamielinux-0x9E5A947BAC2932F8"

- name: "install packages"
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    - "postgresql"
    - "postgresql-devel"

- name: "install packages"
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ item }}"
    update_cache: True
    state: "present"
  with_items:
    - "postgresql-client"
    - "postgresql-server-dev-all"

