---

- include: "facts.yml"
  tags: "always"

- include: "packages-rhel7.yml"
  tags: "opendkim-packages"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "7"

- include: "packages-jessie.yml"
  tags: "opendkim-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "packages-jessie.yml"
  tags: "opendkim-packages"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_version == "15.04"

- include: "configs.yml"
  tags: "opendkim-configs"

- include: "services.yml"
  tags: "opendkim-services"

