---

- name: "install packages required for SELinux"
  when: ansible_selinux.status != "disabled" and ansible_os_family == "RedHat"
  yum:
    name: "policycoreutils"
    update_cache: True
    state: "present"

- name: "install packages required for SELinux"
  when: ansible_selinux.status != "disabled" and ansible_os_family == "Debian"
  apt:
    name: "policycoreutils"
    update_cache: True
    state: "present"

- name: "setsebool -P httpd_can_network_connect 1"
  seboolean:
    name: "httpd_can_network_connect"
    state: True
    persistent: True

