---

- include: "facts.yml"
  tags: "always"

- include: "repo-rhel7.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "7"

- include: "repo-f22.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "22"

- include: "repo-jessie.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "repo-vivid.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_version == "15.04"

