---

- name: "check if pgdg repository exists"
  stat:
    path: "/etc/yum.repos.d/pgdg-{{ postgres_version_short }}-fedora.repo"
  changed_when: False
  register: pgdg_repo

- name: "install pgdg-bootstrap repository"
  when: not pgdg_repo.stat.exists
  template:
    src: "pgdg-{{ postgres_version_short }}-bootstrap.repo.j2"
    dest: "/etc/yum.repos.d/pgdg-{{ postgres_version_short }}-bootstrap.repo"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "install pgdg-bootstrap GPG key"
  when: not pgdg_repo.stat.exists
  copy:
    src: "RPM-GPG-KEY-PGDG-{{ postgres_version_short }}-BOOTSTRAP"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ postgres_version_short }}-BOOTSTRAP"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "install gnupg"
  yum:
    name: "gnupg"
    state: "present"

- name: "import pgdg-bootstrap GPG key"
  when: not pgdg_repo.stat.exists
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ postgres_version_short }}-BOOTSTRAP"
    state: "present"

- name: "install pgdg repository"
  when: not pgdg_repo.stat.exists
  yum:
    enablerepo: "pgdg{{ postgres_version_short }}-bootstrap"
    name: "pgdg-fedora{{ postgres_version_short }}"
    state: "present"

- name: "remove pgdg-bootstrap repository"
  file:
    dest: "/etc/yum.repos.d/pgdg-{{ postgres_version_short }}-bootstrap.repo"
    state: "absent"

- name: "remove pgdg-bootstrap key"
  file:
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ postgres_version_short }}-BOOTSTRAP"
    state: "absent"

