---

- name: "install packages required for SELinux"
  when: ansible_selinux.status != "disabled"
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "policycoreutils"
    - "policycoreutils-python"

- name: "configure SELinux file contexts for PostgreSQL executables"
  when: ansible_selinux.status != "disabled"
  command: >
    /usr/sbin/semanage fcontext -a -t postgresql_exec_t
    "/usr/pgsql-[0-9.]+/bin/.*"
  args:
    creates: "/root/.ansible_semanage_postgresql_exec_t"
  notify:
    - "touch /root/.ansible_semanage_postgresql_exec_t"

- name: "configure SELinux file contexts for PostgreSQL log files"
  when: ansible_selinux.status != "disabled"
  command: >
    /usr/sbin/semanage fcontext -a -t postgresql_log_t
    "/var/lib/pgsql/[0-9.]+/data/pg_log(/.*)?"
  args:
    creates: "/root/.ansible_semanage_postgresql_log_t"
  notify:
    - "touch /root/.ansible_semanage_postgresql_log_t"

- name: "check if pgdg repository exists"
  stat:
    path: "/etc/yum.repos.d/pgdg-{{ postgres_version_short }}-centos.repo"
  changed_when: False
  register: pgdg_repo

- name: "install pgdg-bootstrap repository"
  when: not pgdg_repo.stat.exists
  copy:
    src: "pgdg-{{ postgres_version_short }}-bootstrap.repo"
    dest: "/etc/yum.repos.d/pgdg-{{ postgres_version_short }}-bootstrap.repo"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "install pgdg-bootstrap GPG key"
  when: not pgdg_repo.stat.exists
  copy:
    src: "RPM-GPG-KEY-PGDG-{{ postgres_version_short }}-BOOTSTRAP"
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ postgres_version_short }}-BOOTSTRAP"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "import pgdg-bootstrap GPG key"
  when: not pgdg_repo.stat.exists
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ postgres_version_short }}-BOOTSTRAP"
    state: "present"

- name: "install pgdg repository"
  when: not pgdg_repo.stat.exists
  yum:
    enablerepo: "pgdg{{ postgres_version_short }}-bootstrap"
    name: "pgdg-centos{{ postgres_version_short }}"
    state: "present"

- name: "remove pgdg-bootstrap repository"
  file:
    dest: "/etc/yum.repos.d/pgdg-{{ postgres_version_short }}-bootstrap.repo"
    state: "absent"

- name: "remove pgdg-bootstrap key"
  file:
    dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-PGDG-{{ postgres_version_short }}-BOOTSTRAP"
    state: "absent"

