---

dependencies:
  - role: "epel"
    tags: ["epel"]
    when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"

  - role: "rbenv"
    tags: ["rbenv"]
    rbenv_user: "discourse"
    rbenv_reload: ["discourse-unicorn.service"]

