---

- include: "facts.yml"
  tags: "always"

- include: "selinux.yml"
  tags: "postgres-selinux"
  when: ansible_os_family == "RedHat"

- include: "packages-rhel7.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "7"

- include: "packages-f22.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "RedHat"
    and ansible_distribution_major_version == "22"

- include: "packages-jessie.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_major_version == "8"

- include: "packages-vivid.yml"
  tags: "postgres-repo"
  when: >
    ansible_os_family == "Debian"
    and ansible_distribution_version == "15.04"

- include: "user.yml"
  tags: "postgres-user"

- include: "initdb.yml"
  tags: "postgres-initdb"

- include: "tmpfiles.yml"
  tags: "postgres-tmpfiles"

